FROM python:3.5

MAINTAINER David Lyon <dblyon@gmail.com>
#USER dblyon

ENV PYTHONUNBUFFERED 1
ENV HOME /root
ENV PYTHONPATH "/usr/lib/python3/dist-packages:/usr/local/lib/python3.5/site-packages"

# Install dependencies
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get autoremove -y \
    && apt-get install -y \
        gcc \
        build-essential \
        zlib1g-dev \
        wget \
        unzip \
        cmake \
        python3-dev \
        gfortran \
        libblas-dev \
        liblapack-dev \
        libatlas-base-dev \
        rsync \
        tree \
        vim \
    && apt-get clean

RUN pip install --upgrade pip
# Install Python packages
RUN pip install \
        numpy \
        scipy \
        cython \
        pandas \
        jupyter \
        notebook \
    && rm -fr /root/.cache


RUN mkdir -p /opt/services/flaskapp/src
#VOLUME ["/opt/services/flaskapp/src"]
#RUN echo $PYTHONPATH

# We copy the requirements.txt file first to avoid cache invalidations
COPY ./app/requirements.txt /opt/services/flaskapp/src/
WORKDIR /opt/services/flaskapp/src
RUN pip install -r requirements.txt
COPY ./app /opt/services/flaskapp/src
RUN cd python && python setup.py build_ext --inplace
COPY ./app/.bashrc /root/.bashrc
WORKDIR /opt/services/flaskapp/src
EXPOSE 8888
CMD ["jupyter", "notebook"]