DROP TABLE IF EXISTS functions_temp, protein_2_function_temp, entity_types_temp, taxid_2_protein_temp, go_2_slim_temp, ontologies_temp;

CREATE TABLE functions_temp (
    type text,
    name text,
    an text,
    definition text);
CREATE TABLE protein_2_function_temp (
    an text,
    function text ARRAY,
    etype integer);
CREATE TABLE entity_types_temp (
    an text,
    etype integer,
    name text);
CREATE TABLE taxid_2_protein_temp (
    taxid integer,
    an_array text ARRAY,
    count integer);
CREATE TABLE go_2_slim_temp (
    an text,
    slim boolean);
CREATE TABLE ontologies_temp (
    child text,
    parent text,
    direct boolean,
    type integer);
CREATE TABLE function_2_ensp_temp (
    taxid integer,
    etype integer,
    association text,
    background_count integer,
    background_n integer,
    an_array text ARRAY);


\copy functions_temp FROM '/agotool_data/PostgreSQL/tables/test/Functions_table_STRING.txt';
\copy protein_2_function_temp FROM '/agotool_data/PostgreSQL/tables/test/Protein_2_Function_table_STRING.txt';
\copy entity_types_temp FROM '/agotool_data/PostgreSQL/tables/test/Entity_types_table_STRING.txt';
\copy taxid_2_protein_temp FROM '/agotool_data/PostgreSQL/tables/test/TaxID_2_Proteins_table_STRING.txt';
\copy go_2_slim_temp FROM '/agotool_data/PostgreSQL/tables/test/GO_2_Slim_table_STRING.txt';
\copy ontologies_temp FROM '/agotool_data/PostgreSQL/tables/test/Ontologies_table_STRING.txt';
\copy function_2_ensp_temp FROM '/agotool_data/PostgreSQL/tables/Function_2_ENSP_table_STRING.txt';

CREATE INDEX protein_2_function_an_etype_idx_temp ON protein_2_function_temp (an, etype);
CLUSTER protein_2_function_temp USING protein_2_function_an_etype_idx_temp;
CREATE INDEX function_2_ensp_taxid_idx_temp ON function_2_ensp_temp (taxid);
CREATE INDEX function_2_ensp_taxid_etype_idx_temp ON function_2_ensp_temp (taxid, etype);
CLUSTER function_2_ensp_temp USING function_2_ensp_taxid_etype_idx_temp;