--CREATE DATABASE agotool;

--CREATE TABLE protein_secondary_2_primary_an (
--    taxid integer,
--    sec text,
--    prim text);

\copy protein_secondary_2_primary_an FROM 'data/PostgreSQL/tables/Secondary_2_Primary_IDs_UPS_FIN_for_DB_sorted.txt';
CREATE INDEX protein_secondary_2_primary_an_sec_idx ON protein_secondary_2_primary_an (sec);
CREATE INDEX protein_secondary_2_primary_an_taxid_idx ON protein_secondary_2_primary_an (taxid);
CLUSTER protein_secondary_2_primary_an USING protein_secondary_2_primary_an_taxid_idx;