DROP TABLE IF EXISTS functions, protein_2_function, protein_2_functionenum, entity_types, taxid_2_protein, go_2_slim, ontologies, function_2_ensp;
DROP INDEX IF EXISTS protein_2_function_an_etype_idx, function_2_ensp_taxid_idx, function_2_ensp_taxid_etype_idx, taxid_2_protein_taxid_idx;

CREATE TABLE functions (
    enum integer,
    etype integer,
    an text,
    description text,
    year text,
    level integer);
CREATE TABLE protein_2_functionenum (
    an text,
    functionenum integer ARRAY);
CREATE TABLE entity_types (
    an text,
    etype integer,
    name text);
CREATE TABLE taxid_2_protein (
    taxid integer,
    an_array text ARRAY,
    count integer);
CREATE TABLE go_2_slim (
    an text,
    slim boolean);
CREATE TABLE taxid_2_functioncountarray (
    taxid integer,
    background_n integer,
    background_count_array integer ARRAY);
CREATE TABLE funcenum_2_lineage (
    enum integer,
    enum_array integer ARRAY);

\copy functions FROM '/agotool_data/PostgreSQL/tables/Functions_table_STRING.txt';
\copy protein_2_functionenum FROM '/agotool_data/PostgreSQL/tables/Protein_2_FunctionEnum_table_STRING.txt';
\copy entity_types FROM '/agotool_data/PostgreSQL/tables/Entity_types_table_STRING.txt';
\copy taxid_2_protein FROM '/agotool_data/PostgreSQL/tables/TaxID_2_Proteins_table_STRING.txt';
\copy go_2_slim FROM '/agotool_data/PostgreSQL/tables/GO_2_Slim_table_STRING.txt';
\copy taxid_2_functioncountarray FROM '/agotool_data/PostgreSQL/tables/Taxid_2_FunctionCountArray_table_STRING.txt';
\copy funcenum_2_lineage FROM '/agotool_data/PostgreSQL/tables/Lineage_table_STRING.txt';

CREATE INDEX functions_enum_idx ON functions (enum);
CREATE INDEX functions_an_idx ON functions (an);
CREATE INDEX functions_etype_an_idx ON functions (etype, an);
CLUSTER functions USING functions_etype_an_idx;

CREATE INDEX protein_2_functionenum_an_idx ON protein_2_functionenum (an);

CREATE INDEX taxid_2_functioncountarray_taxid_idx ON taxid_2_functioncountarray (taxid);

CREATE INDEX taxid_2_protein_taxid_idx ON taxid_2_protein (taxid);

--CREATE TABLE protein_2_function(
--    an text,
--    function text ARRAY,
--    etype integer);
--CREATE TABLE functions (
--    etype integer,
--    an text,
--    name text,
--    definition text,
--    description text);
--CREATE TABLE ontologies (
--    child text,
--    parent text,
--    direct boolean,
--    etype integer);
--CREATE TABLE function_2_ensp (
--    taxid integer,
--    etype integer,
--    association text,
--    enum integer,
--    background_count integer,
--    background_n integer,
--    an_array text ARRAY);
--\copy protein_2_function FROM '/agotool_data/PostgreSQL/tables/Protein_2_Function_table_STRING.txt';
--\copy function_2_ensp FROM '/agotool_data/PostgreSQL/tables/Function_2_ENSP_table_STRING.txt';
--\copy ontologies FROM '/agotool_data/PostgreSQL/tables/Ontologies_table_STRING.txt';
--CREATE INDEX protein_2_function_an_idx ON protein_2_function (an);
--CREATE INDEX protein_2_function_an_etype_idx ON protein_2_function (an, etype);
--CLUSTER protein_2_function USING protein_2_function_an_etype_idx;
--CREATE INDEX function_2_ensp_taxid_idx ON function_2_ensp (taxid);
--CREATE INDEX function_2_ensp_taxid_etype_idx ON function_2_ensp (taxid, etype);
--CLUSTER function_2_ensp USING function_2_ensp_taxid_etype_idx;