DROP TABLE IF EXISTS functions, go_2_slim, ogs, og_2_function, ontologies, protein_2_function, protein_secondary_2_primary_an, protein_2_og;

ALTER TABLE functions_temp RENAME TO functions;
ALTER TABLE go_2_slim_temp RENAME TO go_2_slim;
ALTER TABLE ogs_temp RENAME TO ogs;
ALTER TABLE og_2_function_temp RENAME TO og_2_function;
ALTER TABLE ontologies_temp RENAME TO ontologies;
ALTER TABLE protein_2_function_temp RENAME TO protein_2_function;
ALTER TABLE protein_secondary_2_primary_an_temp RENAME TO protein_secondary_2_primary_an;
ALTER TABLE protein_2_og_temp RENAME TO protein_2_og;

ALTER INDEX ogs_og_idx_temp RENAME TO ogs_og_idx;
ALTER INDEX og_2_function_og_idx_temp RENAME TO og_2_function_og_idx;
ALTER INDEX protein_2_function_an_idx_temp RENAME TO protein_2_function_an_idx;
ALTER INDEX protein_2_og_an_idx_temp RENAME TO protein_2_og_an_idx;
