--DROP TABLE IF EXISTS functions;
--CREATE TABLE functions(
--    etype text,
--    an text,
--    name text,
--    definition text,
--    description text);
--\copy functions FROM '/agotool_data/PostgreSQL/tables/Functions_table_STRING.txt';
--CREATE INDEX functions_an_idx ON functions (an);
--CREATE INDEX functions_etype_an_idx ON functions (etype, an);
--CLUSTER functions USING functions_etype_an_idx;

--DROP TABLE IF EXISTS protein_2_function;
--CREATE TABLE protein_2_function(
--    an text,
--    function text ARRAY,
--    etype integer);
--\copy protein_2_function FROM '/agotool_data/PostgreSQL/tables/Protein_2_Function_table_STRING.txt';
--CREATE INDEX protein_2_function_an_idx ON protein_2_function (an);
--CREATE INDEX protein_2_function_an_etype_idx ON protein_2_function (an, etype);
--CLUSTER protein_2_function USING protein_2_function_an_etype_idx;

DROP TABLE IF EXISTS function_2_ensp;
CREATE TABLE function_2_ensp (
    taxid integer,
    etype integer,
    association text,
    background_count integer,
    background_n integer,
    an_array text ARRAY);
\copy function_2_ensp FROM '/agotool_data/PostgreSQL/tables/Function_2_ENSP_table_STRING.txt';
CREATE INDEX function_2_ensp_taxid_idx ON function_2_ensp (taxid);
CREATE INDEX function_2_ensp_taxid_etype_idx ON function_2_ensp (taxid, etype);
CLUSTER function_2_ensp USING function_2_ensp_taxid_etype_idx;
