import numpy as np
import os, sys, psycopg2

def searchsorted_dbl(fg, bg):
    fg.sort()
    bg.sort()
    fg_bg = np.concatenate((fg, bg))
    fg_bg.sort()
    searchsorted_fg, searchsorted_bg = [], []
    fg_rank, bg_rank = 0, 0
    num_fg_vals, num_bg_vals = fg.shape[0], bg.shape[0]
    num_fg_bg_vals = fg_bg.shape[0]
    val_previous = -1
    for val in fg_bg:
        if val == val_previous:
            searchsorted_fg.append(fg_rank)
            continue
        if fg_rank == num_fg_vals:
            searchsorted_fg += [searchsorted_fg[-1]] * (num_fg_bg_vals-len(searchsorted_fg))
            break
        for fg_index in range(fg_rank, num_fg_vals):
            fg_val = fg[fg_index]
            if val < fg_val:
                searchsorted_fg.append(fg_rank)
                break
            else:
                fg_rank += 1
        val_previous = val
    return np.array(searchsorted_fg)#, np.array(searchsorted_bg)


def get_cursor(env_dict=None):
    platform_ = sys.platform
    if env_dict is not None:
        USER = env_dict['POSTGRES_USER']
        PWD = env_dict['POSTGRES_PASSWORD']
        DBNAME = env_dict['POSTGRES_DB']
        PORT = '5432'
        HOST = 'db'
        return get_cursor_docker(host=HOST, dbname=DBNAME, user=USER, password=PWD, port=PORT)

    if platform_ == "linux":
        if not variables.DB_DOCKER: # use local Postgres
            try:
                USER = "postgres"
                PWD = os.environ['POSTGRES_PASSWORD']
                DBNAME = os.environ['POSTGRES_DB']
                PORT = '5432'
                HOST = 'db'
            except KeyError:
                print("query.py sais there is something wrong with the Postgres config")
                raise StopIteration
            return get_cursor_docker(host=HOST, dbname=DBNAME, user=USER, password=PWD, port=PORT)
        else: # use dockerized Postgres directly from native OS
            PORT = '5913'
            HOST = 'localhost'
            param_2_val_dict = variables.param_2_val_dict
            return get_cursor_connect_2_docker(host=HOST, dbname=param_2_val_dict["POSTGRES_DB"], user=param_2_val_dict["POSTGRES_USER"], password=param_2_val_dict["POSTGRES_PASSWORD"], port=PORT)

    elif platform_ == "darwin":
        # if not variables.DB_DOCKER: # use local Postgres
        return get_cursor_ody()
        # else: # connect to docker Postgres container. use dockerized Postgres directly from native OS
        #     PORT = '5432' # shouldn't this be 5913?
        #     HOST = 'localhost'
        #     param_2_val_dict = variables.param_2_val_dict
        #     return get_cursor_connect_2_docker(host=HOST, dbname=param_2_val_dict["POSTGRES_DB"], user=param_2_val_dict["POSTGRES_USER"], password=param_2_val_dict["POSTGRES_PASSWORD"], port=PORT)
    else:
        print("query.get_cursor() doesn't know how to connect to Postgres")
        raise StopIteration

def get_cursor_docker(host, dbname, user, password, port):
    """
    e.g.
    import os
    user = os.environ['POSTGRES_USER']
    pwd = os.environ['POSTGRES_PASSWORD']
    db = os.environ['POSTGRES_DB']
    host = 'db'
    port = '5432'
    cursor = get_cursor_docker(user=user, password=pwd, host=host, port=port, dbname=db)
    # Sqlalchemy version: engine = create_engine('postgres://%s:%s@%s:%s/%s' % (user, pwd, host, port, db))
    """
    # Define our connection string
    # conn_string = "host='{}' dbname='{}' user='{}' password='{}'".format(host, dbname, user, password)

    # engine = create_engine('postgres://%s:%s@%s:%s/%s' % (user, pwd, host, port, db))
    conn_string = "host='{}' dbname='{}' user='{}' password='{}' port='{}'".format(host, dbname, user, password, port)
    # get a connection, if a connect cannot be made an exception will be raised here
    conn = psycopg2.connect(conn_string)

    # conn.cursor will return a cursor object, you can use this cursor to perform queries
    cursor = conn.cursor()
    return cursor

def get_cursor_ody(dbname='agotool'):
    """
    :param dbname:
    :return: DB Cursor instance object
    """
    # Define our connection string
    conn_string = "dbname='{}'".format(dbname)

    # get a connection, if a connect cannot be made an exception will be raised here
    conn = psycopg2.connect(conn_string)

    # conn.cursor will return a cursor object, you can use this cursor to perform queries
    cursor = conn.cursor()
    return cursor

def get_cursor_connect_2_docker(host, dbname, user, password, port):
    conn_string = "host='{}' dbname='{}' user='{}' password='{}' port='{}'".format(host, dbname, user, password, port)
    # get a connection, if a connect cannot be made an exception will be raised here
    conn = psycopg2.connect(conn_string)

    # conn.cursor will return a cursor object, you can use this cursor to perform queries
    cursor = conn.cursor()
    return cursor

def query_example():
    cursor = get_cursor()
    cursor.execute("SELECT * FROM functions LIMIT 5")
    records = cursor.fetchall()
    cursor.close()
    print(records)

def get_results_of_statement(sql_statement):
    cursor = get_cursor()
    cursor.execute(sql_statement)
    result = cursor.fetchall()
    cursor.close()
    return result



def get_functionEnumArray_from_proteins(protein_ans_list, dict_2_array=False):
    """
    ENSP_2_functionEnumArray_dict =
    {'1000565.METUNv1_00006': array([45130, 46056, 46149, 50102, 83861, 95081, 95232], dtype=uint32),
    '1000565.METUNv1_00011': array([45130, 46056, 46149, 70030, 83861, 95232], dtype=uint32), ...
    ENSP_2_funcEnumAssociations =
    [('10090.ENSMUSP00000001812', [52, 280, 282, 405, ...
    which functional associations are present for the given proteins
    variable length array of Integers, each codes for a specific function (enumeration of function)
    int32 Integer (-2147483648 to 2147483647), since enumeration between 0 and 6.815.598 (variables.function_enumeration_len)
    :param protein_ans_list: List of String
    :param dict_2_array: Bool (flag to get a dict of ENSPs with func enum arr as values, otherwise nested list of tuples (ENSP, list of func enums))
    :return: List of Tuple( String(ENSP), List of Integers(function enumeration) )
    """
    # result = get_results_of_statement("SELECT protein_2_functionenum.an, protein_2_functionenum.functionenum FROM protein_2_functionenum WHERE protein_2_functionenum.an IN({});".format(str(protein_ans_list)[1:-1]))
    result = get_results_of_statement("SELECT protein_2_functionenum.id, protein_2_functionenum.functionenum FROM protein_2_functionenum WHERE protein_2_functionenum.id IN({});".format(str(protein_ans_list)[1:-1]))
    if not dict_2_array:
        return result
    else:
        dict_2_return = {}
        for res in result:
            ENSP, list_of_funcEnums = res
            dict_2_return[ENSP] = np.array(list_of_funcEnums, dtype=np.dtype("uint32"))
        return dict_2_return




if __name__ == "__main__":
    if __name__ == "__main__":
        # pqo = PersistentQueryObject_STRING()

        ensp_list = ['I12R1_HUMAN', 'IL17D_HUMAN', 'GATB_HUMAN', 'ING3_HUMAN', 'GALC_HUMAN', 'HIG1C_HUMAN', 'IRAK2_HUMAN', 'GPR19_HUMAN', 'HXA7_HUMAN', 'IL17F_HUMAN', 'GIMA6_HUMAN', 'GP152_HUMAN', 'HDAC8_HUMAN', 'GNL3_HUMAN', 'ISL1_HUMAN', 'GPAA1_HUMAN', 'GALT_HUMAN', 'IRGQ_HUMAN', 'I17RB_HUMAN', 'GOG8J_HUMAN', 'GTSFL_HUMAN', 'HUTU_HUMAN', 'GNB1L_HUMAN', 'IL33_HUMAN', 'H2AW_HUMAN', 'IFT57_HUMAN', 'INLR1_HUMAN', 'HXB8_HUMAN', 'GLYL3_HUMAN', 'HGFL_HUMAN', 'HXC12_HUMAN', 'IFN21_HUMAN', 'GATA5_HUMAN', 'GRIA3_HUMAN', 'HRH3_HUMAN', 'IFIT1_HUMAN', 'IFM1_HUMAN', 'HEM3_HUMAN', 'IL27A_HUMAN', 'IGS22_HUMAN', 'IGKC_HUMAN', 'IKBD_HUMAN', 'GGNB2_HUMAN', 'GSTCD_HUMAN', 'GOG8H_HUMAN', 'GPS2_HUMAN', 'HCN4_HUMAN', 'IF5A2_HUMAN', 'GPBAR_HUMAN', 'GOG6A_HUMAN', 'GTR2_HUMAN', 'GATD1_HUMAN', 'HXC11_HUMAN', 'GDPD2_HUMAN', 'HV338_HUMAN', 'GPR22_HUMAN', 'HTR5A_HUMAN', 'HS90A_HUMAN', 'HXD13_HUMAN', 'GOG8N_HUMAN', 'IEX1_HUMAN', 'GDPP1_HUMAN', 'HXK2_HUMAN', 'IKZF2_HUMAN', 'HS74L_HUMAN', 'ILVBL_HUMAN',
                     'GALK1_HUMAN', 'HPSE_HUMAN', 'ITA1_HUMAN', 'IHO1_HUMAN', 'HMMR_HUMAN', 'GRCR2_HUMAN', 'GLIS3_HUMAN', 'IGLO5_HUMAN', 'GPR62_HUMAN', 'HS3S6_HUMAN', 'INT6L_HUMAN', 'GNAO_HUMAN', 'IL2RA_HUMAN', 'HHLA1_HUMAN', 'GRAH_HUMAN', 'GUC2D_HUMAN', 'GNDS_HUMAN', 'IGFL2_HUMAN', 'HME2_HUMAN', 'IMA5_HUMAN', 'HS3S2_HUMAN', 'H1FNT_HUMAN', 'GRIP2_HUMAN', 'GPSM1_HUMAN', 'HUNIN_HUMAN', 'GDF5O_HUMAN', 'HUTH_HUMAN', 'HDGR3_HUMAN', 'GLI4_HUMAN', 'HNRC1_HUMAN', 'ISLR2_HUMAN', 'GPM6B_HUMAN', 'IRX2_HUMAN', 'GUC2C_HUMAN', 'IFNL4_HUMAN', 'GIMA1_HUMAN', 'HXA1_HUMAN', 'GPBL1_HUMAN', 'GEN_HUMAN', 'GPCP1_HUMAN', 'IKIP_HUMAN', 'GG12F_HUMAN', 'HNRH3_HUMAN', 'GPTC4_HUMAN', 'GIMA7_HUMAN', 'IPP2L_HUMAN', 'GLT17_HUMAN', 'GP153_HUMAN', 'IVD_HUMAN', 'GRASP_HUMAN', 'GCYB1_HUMAN', 'IGSF5_HUMAN', 'IFNA8_HUMAN', 'IL1FA_HUMAN', 'HLTF_HUMAN', 'HS905_HUMAN', 'GSX2_HUMAN', 'HBEGF_HUMAN', 'HELQ_HUMAN', 'IFT56_HUMAN', 'GEMI_HUMAN', 'HDHD5_HUMAN', 'GLB1L_HUMAN', 'GBP2_HUMAN', 'GREB1_HUMAN', 'HXD8_HUMAN',
                     'I20L2_HUMAN', 'GPER1_HUMAN', 'HCN2_HUMAN', 'HV316_HUMAN', 'INT14_HUMAN', 'GCYB2_HUMAN', 'GG6L4_HUMAN', 'HMOX2_HUMAN', 'GMFB_HUMAN', 'GFI1B_HUMAN', 'HBAP1_HUMAN', 'INAR2_HUMAN', 'HV364_HUMAN', 'HV307_HUMAN', 'HASP_HUMAN', 'IFNE_HUMAN', 'GBG4_HUMAN', 'HEAT4_HUMAN', 'GPR78_HUMAN', 'GPC1_HUMAN', 'HNRPD_HUMAN', 'HXB9_HUMAN', 'IL21R_HUMAN', 'IFT25_HUMAN', 'GASP1_HUMAN', 'HEM6_HUMAN', 'GBP4_HUMAN', 'IFI44_HUMAN', 'GATA1_HUMAN', 'IPO7_HUMAN', 'HELLS_HUMAN', 'HLF_HUMAN', 'HPIP_HUMAN', 'IBP1_HUMAN', 'HNRC4_HUMAN', 'GDIB_HUMAN', 'HSPB9_HUMAN', 'GP108_HUMAN', 'IF1AX_HUMAN', 'GOG8S_HUMAN', 'GPHRA_HUMAN', 'HCDH_HUMAN', 'GXLT1_HUMAN', 'HMCES_HUMAN', 'HOP2_HUMAN', 'ITB8_HUMAN', 'GAK_HUMAN', 'IP3KC_HUMAN', 'IFIT3_HUMAN', 'GRIK3_HUMAN', 'GPAN1_HUMAN', 'HDAC2_HUMAN', 'HSF4_HUMAN', 'ITA4_HUMAN', 'HUNK_HUMAN', 'IKBZ_HUMAN', 'IN80B_HUMAN', 'IDHP_HUMAN', 'IQCF1_HUMAN', 'HYALP_HUMAN', 'IL17C_HUMAN', 'IL17B_HUMAN', 'INT12_HUMAN', 'IFNA7_HUMAN', 'GLPK3_HUMAN', 'HEN2_HUMAN', 'GDE1_HUMAN',
                     'GCNT4_HUMAN', 'IGJ_HUMAN', 'INS_HUMAN', 'IL1RA_HUMAN', 'GARS_HUMAN', 'GOLI4_HUMAN', 'HDGF_HUMAN', 'GSDMB_HUMAN', 'GRB7_HUMAN', 'IF4G1_HUMAN', 'GIPC1_HUMAN', 'GNMT_HUMAN', 'IGF1R_HUMAN', 'ILF2_HUMAN', 'INHBE_HUMAN', 'ITAM_HUMAN', 'GBG10_HUMAN', 'HAUS5_HUMAN', 'GG12G_HUMAN', 'HYKK_HUMAN', 'GUC1B_HUMAN', 'IGDC4_HUMAN', 'INADL_HUMAN', 'IIGP5_HUMAN', 'INT5_HUMAN', 'GP1BA_HUMAN', 'G3ST1_HUMAN', 'HEAT9_HUMAN', 'GP149_HUMAN', 'GP157_HUMAN', 'IMPA1_HUMAN', 'ITPR3_HUMAN', 'IL1B_HUMAN', 'IBP4_HUMAN', 'HLAA_HUMAN', 'ITIH2_HUMAN', 'HS3S4_HUMAN', 'GPR75_HUMAN', 'GRSF1_HUMAN', 'IGS21_HUMAN', 'GSG1_HUMAN', 'HDAC6_HUMAN', 'HPHL1_HUMAN', 'GPR35_HUMAN', 'GNTK_HUMAN', 'GP132_HUMAN', 'IDS_HUMAN', 'GTD2A_HUMAN', 'GATA4_HUMAN', 'HAUS2_HUMAN', 'GAK1A_HUMAN', 'I27L2_HUMAN', 'ITPR2_HUMAN', 'GO45_HUMAN', 'HNRPM_HUMAN', 'GON1_HUMAN', 'ICAM3_HUMAN', 'GCH1_HUMAN', 'GOG6C_HUMAN', 'HUTI_HUMAN', 'INSM1_HUMAN', 'IL9R_HUMAN', 'GTD2B_HUMAN', 'GRHL3_HUMAN', 'GVQW2_HUMAN', 'JAM3_HUMAN',
                     'HMGX3_HUMAN', 'IMA4_HUMAN', 'I10R2_HUMAN', 'GFRA1_HUMAN', 'GLPB_HUMAN', 'HPCA_HUMAN', 'I11RA_HUMAN', 'GSTT2_HUMAN', 'HDAC3_HUMAN', 'GPHRB_HUMAN', 'INKA1_HUMAN', 'GBRL3_HUMAN', 'GFOD1_HUMAN', 'GOGA2_HUMAN', 'IRF2_HUMAN', 'HERC6_HUMAN', 'GDS1_HUMAN', 'HYLS1_HUMAN', 'IN80C_HUMAN', 'INT6_HUMAN', 'INVS_HUMAN', 'GBG1_HUMAN', 'GPR26_HUMAN', 'HTRA3_HUMAN', 'GLGB_HUMAN', 'HAX1_HUMAN', 'HOME2_HUMAN', 'HIKES_HUMAN', 'IQCF6_HUMAN', 'IQCN_HUMAN', 'ITA7_HUMAN', 'IKKA_HUMAN', 'GPN3_HUMAN', 'GLIS1_HUMAN', 'GPC5D_HUMAN', 'GLTD2_HUMAN', 'GBG12_HUMAN', 'GAGE7_HUMAN', 'GSTP1_HUMAN', 'GNPAT_HUMAN', 'INSY2_HUMAN', 'GGCT_HUMAN', 'GP119_HUMAN', 'GLI2_HUMAN', 'IF2M_HUMAN', 'IL19_HUMAN', 'GPR83_HUMAN', 'ITIH4_HUMAN', 'HSH2D_HUMAN', 'GPR42_HUMAN', 'GRB2_HUMAN', 'IF4E3_HUMAN', 'GBRAP_HUMAN', 'HAUS6_HUMAN', 'HPGDS_HUMAN', 'GP158_HUMAN', 'INT1_HUMAN', 'H31_HUMAN', 'H2B2E_HUMAN', 'GP143_HUMAN', 'HM20A_HUMAN', 'GBRR3_HUMAN', 'HGNAT_HUMAN', 'GALD1_HUMAN', 'GSTT1_HUMAN', 'GZF1_HUMAN',
                     'GALR1_HUMAN', 'GLRX5_HUMAN', 'HFE_HUMAN', 'GA45G_HUMAN', 'HMGB4_HUMAN', 'GAN_HUMAN', 'HEXA_HUMAN', 'IL25_HUMAN', 'HEYL_HUMAN', 'GIPR_HUMAN', 'GRK5_HUMAN', 'GALT5_HUMAN', 'HBM_HUMAN', 'HNF6_HUMAN', 'G3PT_HUMAN', 'HYAL2_HUMAN', 'HUS1B_HUMAN', 'HXC5_HUMAN', 'IGLC3_HUMAN', 'GOG8K_HUMAN', 'GTR11_HUMAN', 'GATC_HUMAN', 'HIC2_HUMAN', 'IFI6_HUMAN', 'GEMI5_HUMAN', 'HEPS_HUMAN', 'IL13_HUMAN', 'HINT3_HUMAN', 'GOGA7_HUMAN', 'IRF9_HUMAN', 'GSG1L_HUMAN', 'IL31_HUMAN', 'GIMA4_HUMAN', 'GSLG1_HUMAN', 'GSTM1_HUMAN', 'GBP1_HUMAN', 'HECD1_HUMAN', 'IFT46_HUMAN', 'IN80D_HUMAN', 'ISLR_HUMAN', 'GBRL1_HUMAN', 'H2B2F_HUMAN', 'IL36A_HUMAN', 'HHEX_HUMAN', 'IZUM2_HUMAN', 'GBG14_HUMAN', 'HV158_HUMAN', 'ITB2_HUMAN', 'GIT2_HUMAN', 'GBB2_HUMAN', 'GPAT2_HUMAN', 'HNRL1_HUMAN', 'GANC_HUMAN', 'GLRA3_HUMAN', 'IKZF5_HUMAN', 'IRX1_HUMAN', 'H1T_HUMAN', 'GTPB6_HUMAN', 'H2A2A_HUMAN', 'GRM1_HUMAN', 'GAG2A_HUMAN', 'IGHG3_HUMAN', 'IGSF8_HUMAN', 'GA45B_HUMAN', 'IFT1B_HUMAN', 'HFM1_HUMAN', 'GTSF1_HUMAN',
                     'GLP3L_HUMAN', 'GGTL1_HUMAN', 'GNT2A_HUMAN', 'HIF1N_HUMAN', 'HAGHL_HUMAN', 'HV169_HUMAN', 'IGLC2_HUMAN', 'HNRH1_HUMAN', 'IKBP1_HUMAN', 'IOD3_HUMAN', 'GMEB1_HUMAN', 'GRM7_HUMAN', 'HERC1_HUMAN', 'HENMT_HUMAN', 'IBTK_HUMAN', 'I13R2_HUMAN', 'IFNW1_HUMAN', 'HES7_HUMAN', 'GOG8F_HUMAN', 'HUMMR_HUMAN', 'HACL1_HUMAN', 'IL26_HUMAN', 'HACD2_HUMAN', 'GAST_HUMAN', 'HBE_HUMAN', 'INO80_HUMAN', 'GPAM1_HUMAN', 'H0YIK9_HUMAN', 'GNAI2_HUMAN', 'GTR10_HUMAN', 'HTRA4_HUMAN', 'GABPA_HUMAN', 'GGTA1_HUMAN', 'GOG6B_HUMAN', 'IMP2L_HUMAN', 'HCAR2_HUMAN', 'IF4A1_HUMAN', 'HV349_HUMAN', 'GP148_HUMAN', 'GABR2_HUMAN', 'GGPPS_HUMAN', 'GGTL3_HUMAN', 'HDHD1_HUMAN', 'HMN6_HUMAN', 'HME1_HUMAN', 'GOLP3_HUMAN', 'GDF8_HUMAN', 'IPO8_HUMAN', 'GFRP_HUMAN', 'GTR7_HUMAN', 'GBG2_HUMAN', 'INP4B_HUMAN', 'GNAI1_HUMAN', 'HV330_HUMAN', 'I18RA_HUMAN', 'HAP40_HUMAN', 'HSF2_HUMAN', 'IKBL1_HUMAN', 'GBRA5_HUMAN', 'GALE_HUMAN', 'GPIX_HUMAN', 'GRAK_HUMAN', 'GLIS2_HUMAN', 'HNRL2_HUMAN', 'GHR_HUMAN', 'G6B_HUMAN',
                     'HMCN2_HUMAN', 'INT7_HUMAN', 'GNL1_HUMAN', 'ITPA_HUMAN', 'IFT80_HUMAN', 'G3ST4_HUMAN', 'INT8_HUMAN', 'HHLA3_HUMAN', 'GRPR_HUMAN', 'GOLI_HUMAN', 'GP179_HUMAN', 'GID4_HUMAN', 'GTSE1_HUMAN', 'HORN_HUMAN', 'HMX1_HUMAN', 'GLYLB_HUMAN', 'IF172_HUMAN', 'HIPL2_HUMAN', 'IGIP_HUMAN', 'GG6L6_HUMAN', 'GORS1_HUMAN', 'IF2B3_HUMAN', 'GPT2L_HUMAN', 'HRK_HUMAN', 'IFN10_HUMAN', 'GNL3L_HUMAN', 'HACE1_HUMAN', 'I23O1_HUMAN', 'G32P1_HUMAN', 'IGFR1_HUMAN', 'ISCU_HUMAN', 'HVD82_HUMAN', 'HERP2_HUMAN', 'GPR18_HUMAN', 'GBA3_HUMAN', 'GLSK_HUMAN', 'GCN1_HUMAN', 'HACD1_HUMAN', 'H3Y_HUMAN', 'IBP2_HUMAN', 'I2BPL_HUMAN', 'IMPA2_HUMAN', 'GLPA_HUMAN', 'IL5_HUMAN', 'IL18_HUMAN', 'IDH3G_HUMAN', 'ITA11_HUMAN', 'GALA_HUMAN', 'G3ST3_HUMAN', 'GRIN2_HUMAN', 'GPT_HUMAN', 'HIPL1_HUMAN', 'H2B1K_HUMAN', 'INT3_HUMAN', 'HDX_HUMAN', 'GARE1_HUMAN', 'GTF2I_HUMAN', 'HV69D_HUMAN', 'GAG13_HUMAN', 'IF4G2_HUMAN', 'GG6L3_HUMAN', 'GSDME_HUMAN', 'GLYG_HUMAN', 'GALK2_HUMAN', 'GSK3B_HUMAN', 'HXD11_HUMAN', 'GSTK1_HUMAN',
                     'HDAC1_HUMAN', 'GPR52_HUMAN', 'GOGA3_HUMAN', 'IDI1_HUMAN', 'GPX5_HUMAN', 'GPI8_HUMAN', 'HDBP1_HUMAN', 'HV741_HUMAN', 'HSPB6_HUMAN', 'IL10_HUMAN', 'HBG2_HUMAN', 'IL23R_HUMAN', 'GA2L2_HUMAN', 'IF44L_HUMAN', 'HERC2_HUMAN', 'IPO13_HUMAN', 'ITAE_HUMAN', 'HEM2_HUMAN', 'HSBPL_HUMAN', 'GRK4_HUMAN', 'GARE2_HUMAN', 'GP174_HUMAN', 'G6PC_HUMAN', 'GRK7_HUMAN', 'IFIX_HUMAN', 'HV434_HUMAN', 'GDAP2_HUMAN', 'GHDC_HUMAN', 'ITA2B_HUMAN', 'GCP60_HUMAN', 'GBX1_HUMAN', 'GPR63_HUMAN', 'IQCB1_HUMAN', 'JAM1_HUMAN', 'GT251_HUMAN', 'GBRB1_HUMAN', 'HMHB1_HUMAN', 'GMPPA_HUMAN', 'HXA6_HUMAN', 'IMA3_HUMAN', 'HID1_HUMAN', 'GFI1_HUMAN', 'GLOD5_HUMAN', 'I17RC_HUMAN', 'G3BP2_HUMAN', 'HOME3_HUMAN', 'IL32_HUMAN', 'IFT52_HUMAN', 'HSP76_HUMAN', 'H2A1H_HUMAN', 'GCP5_HUMAN', 'GRAM_HUMAN', 'IBPL1_HUMAN', 'INSRR_HUMAN', 'ICOSL_HUMAN', 'IMUP_HUMAN', 'HACD3_HUMAN', 'HV432_HUMAN', 'GGT1_HUMAN', 'GYS1_HUMAN', 'GOG8Q_HUMAN', 'GNLY_HUMAN', 'HXB4_HUMAN', 'IF5AL_HUMAN', 'GSTM5_HUMAN', 'IL3_HUMAN', 'ITA2_HUMAN',
                     'JAZF1_HUMAN', 'GG12C_HUMAN', 'GBRG2_HUMAN', 'GLSL_HUMAN', 'HMHA1_HUMAN', 'IRF8_HUMAN', 'GAFA1_HUMAN', 'IFT20_HUMAN', 'IGSF6_HUMAN', 'HMN7_HUMAN', 'GPTC1_HUMAN', 'GAG10_HUMAN', 'HV311_HUMAN', 'IL16_HUMAN', 'GDF2_HUMAN', 'HMN12_HUMAN', 'HRG_HUMAN', 'H2B1D_HUMAN', 'GDIR2_HUMAN', 'GIN1_HUMAN', 'GBRD_HUMAN', 'GRIN1_HUMAN', 'HNRPL_HUMAN', 'HXK1_HUMAN', 'GLI1_HUMAN', 'GUSP1_HUMAN', 'HMGA2_HUMAN', 'GOG8C_HUMAN', 'GPAT1_HUMAN', 'HEAS1_HUMAN', 'ITK_HUMAN', 'IGHD_HUMAN', 'H4_HUMAN', 'HDDC2_HUMAN', 'IGLC7_HUMAN', 'HSP13_HUMAN', 'GPR82_HUMAN', 'GLNA_HUMAN', 'GPR55_HUMAN', 'IFT81_HUMAN', 'H31T_HUMAN', 'GABP1_HUMAN', 'GP183_HUMAN', 'HP1B3_HUMAN', 'IPP2_HUMAN', 'IL17_HUMAN', 'GLP2R_HUMAN', 'H3X_HUMAN', 'HBAT_HUMAN', 'HEXI1_HUMAN', 'IRX5_HUMAN', 'GKN1_HUMAN', 'GALT6_HUMAN', 'HV226_HUMAN', 'HM20B_HUMAN', 'JADE3_HUMAN', 'HARB1_HUMAN', 'HNRDL_HUMAN', 'IF2B1_HUMAN', 'H14_HUMAN', 'INHBA_HUMAN', 'IDLC_HUMAN', 'GG12I_HUMAN', 'HGB1A_HUMAN', 'ITIH3_HUMAN', 'GGTL2_HUMAN', 'GDAP1_HUMAN',
                     'GDF10_HUMAN', 'GBP7_HUMAN', 'IF4B_HUMAN', 'ILDR1_HUMAN', 'IL6RA_HUMAN', 'GML_HUMAN', 'HILS1_HUMAN', 'HPCL4_HUMAN', 'HMX3_HUMAN', 'GCYA2_HUMAN', 'H2B3B_HUMAN', 'GBRG1_HUMAN', 'H2B1O_HUMAN', 'ISPD_HUMAN', 'GSTA3_HUMAN', 'IQEC2_HUMAN', 'HXA4_HUMAN', 'GAG2B_HUMAN', 'HAP28_HUMAN', 'HUWE1_HUMAN', 'I17RD_HUMAN', 'HEXB_HUMAN', 'IGLC1_HUMAN', 'GGT2_HUMAN', 'ISK7_HUMAN', 'ILRL1_HUMAN', 'GDF7_HUMAN', 'GG6L1_HUMAN', 'ISK8_HUMAN', 'HEM1_HUMAN', 'HMN10_HUMAN', 'JAG1_HUMAN', 'ITF2_HUMAN', 'GLTP_HUMAN', 'HSFX3_HUMAN', 'GFRA2_HUMAN', 'GLBL2_HUMAN', 'GCP6_HUMAN', 'I2BP1_HUMAN', 'ITM2B_HUMAN', 'HOOK2_HUMAN', 'INSL5_HUMAN', 'JCAD_HUMAN', 'GNAL_HUMAN', 'GEMI8_HUMAN', 'GLI3_HUMAN', 'ICT1_HUMAN', 'GRB1L_HUMAN', 'HEAT6_HUMAN', 'G3BP1_HUMAN', 'IQCM_HUMAN', 'GSAML_HUMAN', 'GHITM_HUMAN', 'ITM2A_HUMAN', 'GSTM4_HUMAN', 'GIMD1_HUMAN', 'HGD_HUMAN', 'GLT11_HUMAN', 'GYS2_HUMAN', 'HV270_HUMAN', 'IP6K3_HUMAN', 'HLAB_HUMAN', 'GPR88_HUMAN', 'HEM4_HUMAN', 'HIPK1_HUMAN', 'HAUS8_HUMAN', 'GIP_HUMAN',
                     'IBADT_HUMAN', 'GPR85_HUMAN', 'HSPB1_HUMAN', 'HDA10_HUMAN', 'IQCJ_HUMAN', 'GUAD_HUMAN', 'IDH3B_HUMAN', 'HIRA_HUMAN', 'IF2B2_HUMAN', 'GSHB_HUMAN', 'IF16_HUMAN', 'GLYC_HUMAN', 'GASR_HUMAN', 'GDIA_HUMAN', 'GMDS_HUMAN', 'IKKE_HUMAN', 'HYPK_HUMAN', 'IL2_HUMAN', 'IQGA2_HUMAN', 'GCC2_HUMAN', 'GET4_HUMAN', 'GABP2_HUMAN', 'HRES1_HUMAN', 'GIMA8_HUMAN', 'G37L1_HUMAN', 'HVCN1_HUMAN', 'HV146_HUMAN', 'GTDC1_HUMAN', 'GTR3_HUMAN', 'IGHE_HUMAN', 'HYAS1_HUMAN', 'GCP4_HUMAN', 'HELB_HUMAN', 'IL31R_HUMAN', 'IQGA3_HUMAN', 'GBG3_HUMAN', 'H2B1A_HUMAN', 'ITB7_HUMAN', 'H0YIQ5_HUMAN', 'HMOX1_HUMAN', 'IGF1_HUMAN', 'HCAR3_HUMAN', 'GLPE_HUMAN', 'IGHM_HUMAN', 'GCM1_HUMAN', 'IZUM3_HUMAN', 'GRM6_HUMAN', 'GPHA2_HUMAN', 'IGHA2_HUMAN', 'HNF1A_HUMAN', 'GLUC_HUMAN', 'HMGN2_HUMAN', 'INSR_HUMAN', 'GDF3_HUMAN', 'GSK3A_HUMAN', 'HEP2_HUMAN', 'GP141_HUMAN', 'HNF1B_HUMAN', 'GANP_HUMAN', 'GPDA_HUMAN', 'HLAH_HUMAN', 'HV335_HUMAN', 'IF2P_HUMAN', 'ISK13_HUMAN', 'GSE1_HUMAN', 'GALM_HUMAN', 'IQCF5_HUMAN',
                     'JAM2_HUMAN', 'IN35_HUMAN', 'HORM2_HUMAN', 'GBRA1_HUMAN', 'H6ST2_HUMAN', 'HMGX4_HUMAN', 'HMSD_HUMAN', 'IFNL3_HUMAN', 'HG2A_HUMAN', 'HERP1_HUMAN', 'GTR1_HUMAN', 'ING2_HUMAN', 'GLT14_HUMAN', 'GRK6_HUMAN', 'H2A1A_HUMAN', 'IFM2_HUMAN', 'IRS4_HUMAN', 'GT2D1_HUMAN', 'H0YIQ3_HUMAN', 'HNMT_HUMAN', 'IBP6_HUMAN', 'GP150_HUMAN', 'I12R2_HUMAN', 'IQCC_HUMAN', 'GPV_HUMAN', 'IL23A_HUMAN', 'G6PT3_HUMAN', 'IFFO1_HUMAN', 'INSI1_HUMAN', 'GPSM3_HUMAN', 'GASP2_HUMAN', 'IPPK_HUMAN', 'IPKG_HUMAN', 'GSHR_HUMAN', 'GP2_HUMAN', 'IRS2_HUMAN', 'HS902_HUMAN', 'IL4RA_HUMAN', 'GP107_HUMAN', 'ITAV_HUMAN', 'GGH_HUMAN', 'IQGA1_HUMAN', 'IDH3A_HUMAN', 'HV103_HUMAN', 'HIG1A_HUMAN', 'H2A2C_HUMAN', 'HAOX2_HUMAN', 'HMGN5_HUMAN', 'GS1L2_HUMAN', 'IRX4_HUMAN', 'GPT11_HUMAN', 'GHRL_HUMAN', 'GGA2_HUMAN', 'GRM4_HUMAN', 'H2AV_HUMAN', 'HIPK4_HUMAN', 'INT2_HUMAN', 'GCNT3_HUMAN', 'HV428_HUMAN', 'HV320_HUMAN', 'GAL3B_HUMAN', 'HV315_HUMAN', 'GL8D1_HUMAN', 'ITCH_HUMAN', 'GT253_HUMAN', 'ISG15_HUMAN', 'IMPG2_HUMAN',
                     'GALT2_HUMAN', 'GOG8A_HUMAN', 'GPR21_HUMAN', 'IPIL2_HUMAN', 'GST2_HUMAN', 'JADE2_HUMAN', 'GRP3_HUMAN', 'ITA3_HUMAN', 'GNRR2_HUMAN', 'HERC4_HUMAN', 'GLOD4_HUMAN', 'HABP2_HUMAN', 'GRIA2_HUMAN', 'GLP1R_HUMAN', 'GKAP1_HUMAN', 'GLR_HUMAN', 'H2B1J_HUMAN', 'INT10_HUMAN', 'HXA11_HUMAN', 'JAK2_HUMAN', 'HMCN1_HUMAN', 'GANAB_HUMAN', 'GROA_HUMAN', 'HPLN1_HUMAN', 'IPKA_HUMAN', 'HSP7C_HUMAN', 'G45IP_HUMAN', 'IF2B_HUMAN', 'IFNA4_HUMAN', 'IRF5_HUMAN', 'GPHB5_HUMAN', 'ICLN_HUMAN', 'GOG8O_HUMAN', 'IF4E_HUMAN', 'GLT13_HUMAN', 'GOT1A_HUMAN', 'JADE1_HUMAN', 'GLT18_HUMAN', 'GLUCM_HUMAN', 'ILKAP_HUMAN', 'GAB3_HUMAN', 'HAT1_HUMAN', 'HXA13_HUMAN', 'IFNA5_HUMAN', 'HEPN1_HUMAN', 'HSFX1_HUMAN', 'ICEF1_HUMAN', 'GPR4_HUMAN', 'HIP1R_HUMAN', 'GCC1_HUMAN', 'GSTM2_HUMAN', 'HLPDA_HUMAN', 'ID3_HUMAN', 'GBGT2_HUMAN', 'HMGN3_HUMAN', 'INKA2_HUMAN', 'IP3KB_HUMAN', 'GOGA5_HUMAN', 'ISK14_HUMAN', 'INO1_HUMAN', 'GNA11_HUMAN', 'GOG8T_HUMAN', 'GBB1_HUMAN', 'GR6_HUMAN', 'ITGBL_HUMAN', 'GRAN_HUMAN',
                     'INAVA_HUMAN', 'HEMGN_HUMAN', 'HGS_HUMAN', 'HEMO_HUMAN', 'GRAPL_HUMAN', 'IKZF1_HUMAN', 'ICA69_HUMAN', 'GPR6_HUMAN', 'GNAQ_HUMAN', 'IWS1_HUMAN', 'HEPH_HUMAN', 'ICA1L_HUMAN', 'IL15_HUMAN', 'GPA33_HUMAN', 'GNPTA_HUMAN', 'HV323_HUMAN', 'IL34_HUMAN', 'HECD3_HUMAN', 'ITSN1_HUMAN', 'G3P_HUMAN', 'GA2L3_HUMAN', 'HEY1_HUMAN', 'INGR2_HUMAN', 'HSP1_HUMAN', 'ITLN1_HUMAN', 'HRCT1_HUMAN', 'HSPB8_HUMAN', 'ITB1_HUMAN', 'IMA7_HUMAN', 'IFNA6_HUMAN', 'GPR39_HUMAN', 'ISY1_HUMAN', 'GPN2_HUMAN', 'IL2RB_HUMAN', 'HPS3_HUMAN', 'HSP72_HUMAN', 'GRTP1_HUMAN', 'IDD_HUMAN', 'GPR1_HUMAN', 'HMN4_HUMAN', 'H4G_HUMAN', 'GRPL2_HUMAN', 'GAPR1_HUMAN', 'GLRX1_HUMAN', 'G6PI_HUMAN', 'GOG6D_HUMAN', 'GPX1_HUMAN', 'GLCM_HUMAN', 'GDE_HUMAN', 'GSH1_HUMAN', 'GMPR2_HUMAN', 'GCM2_HUMAN', 'GP101_HUMAN', 'GLYG2_HUMAN', 'IQIP1_HUMAN', 'HIC1_HUMAN', 'HELZ_HUMAN', 'HEXI2_HUMAN', 'HV781_HUMAN', 'HIP1_HUMAN', 'IL36B_HUMAN', 'GSC2_HUMAN', 'HV439_HUMAN', 'HS3S1_HUMAN', 'IKBE_HUMAN', 'GPC4_HUMAN', 'INCE_HUMAN',
                     'I20RA_HUMAN', 'HAVR2_HUMAN', 'HXK3_HUMAN', 'HS71L_HUMAN', 'I27L1_HUMAN', 'IRS1_HUMAN', 'HEN1_HUMAN', 'INHBC_HUMAN', 'IL11_HUMAN', 'GPR61_HUMAN', 'HIRP3_HUMAN', 'GDPD4_HUMAN', 'H3C_HUMAN', 'GNRHR_HUMAN', 'GMCL1_HUMAN', 'GNPTG_HUMAN', 'GCP2_HUMAN', 'HXC6_HUMAN', 'HTF4_HUMAN', 'HS904_HUMAN', 'IP6K1_HUMAN', 'GBRT_HUMAN', 'GORAB_HUMAN', 'IN80E_HUMAN', 'GAMT_HUMAN', 'GBG13_HUMAN', 'GP162_HUMAN', 'GLYAT_HUMAN', 'IRAK1_HUMAN', 'GP176_HUMAN', 'H17B6_HUMAN', 'GOG8B_HUMAN', 'G5E9R7_HUMAN', 'HD101_HUMAN', 'HINT2_HUMAN', 'HVC33_HUMAN', 'GP182_HUMAN', 'IL37_HUMAN', 'GON2_HUMAN', 'HPSE2_HUMAN', 'GPX6_HUMAN', 'HYOU1_HUMAN', 'HSFX4_HUMAN', 'IFNB_HUMAN', 'GON4L_HUMAN', 'ITA6_HUMAN', 'HNF4A_HUMAN', 'ITLN2_HUMAN', 'GLRA1_HUMAN', 'GPX4_HUMAN', 'G137C_HUMAN', 'ICOS_HUMAN', 'GLCM1_HUMAN', 'HPS5_HUMAN', 'GRDN_HUMAN', 'GTPB1_HUMAN', 'I13R1_HUMAN', 'GRIN3_HUMAN', 'HDA11_HUMAN', 'IPP2B_HUMAN', 'IL1A_HUMAN', 'IF3M_HUMAN', 'GPC6A_HUMAN', 'IL21_HUMAN', 'IL2RG_HUMAN', 'GG12J_HUMAN',
                     'HBS1L_HUMAN', 'HXB7_HUMAN', 'GPVI_HUMAN', 'IR3IP_HUMAN', 'HNRPF_HUMAN', 'HCFC2_HUMAN', 'GFRA4_HUMAN', 'ITFG2_HUMAN', 'HXB5_HUMAN', 'HMGB2_HUMAN', 'IOD2_HUMAN', 'HTRA1_HUMAN', 'GGT5_HUMAN', 'JAK3_HUMAN', 'IL6_HUMAN', 'HDAC7_HUMAN', 'GLT10_HUMAN', 'GLO2_HUMAN', 'I17RE_HUMAN', 'GBRE_HUMAN', 'IGLL5_HUMAN', 'IF1AY_HUMAN', 'IYD1_HUMAN', 'GBRP_HUMAN', 'IFIH1_HUMAN', 'GPAT3_HUMAN', 'GG6L2_HUMAN', 'INT11_HUMAN', 'GBRR2_HUMAN', 'ITIH1_HUMAN', 'GSDMD_HUMAN', 'GLMP_HUMAN', 'IFAS1_HUMAN', 'GLIP1_HUMAN', 'GPR27_HUMAN', 'HMN8_HUMAN', 'INT13_HUMAN', 'GRAM4_HUMAN', 'H2AJ_HUMAN', 'GDF6_HUMAN', 'IG2AS_HUMAN', 'INGR1_HUMAN', 'HAIR_HUMAN', 'HYPDH_HUMAN', 'HMGB1_HUMAN', 'IFM5_HUMAN', 'GLPC_HUMAN', 'GSKIP_HUMAN', 'IBP3_HUMAN', 'ISK5_HUMAN', 'HXC8_HUMAN', 'IFT43_HUMAN', 'GRP75_HUMAN', 'GRM8_HUMAN', 'HDAC4_HUMAN', 'HSF5_HUMAN', 'GNB5_HUMAN', 'HIG1B_HUMAN', 'GRB10_HUMAN', 'HNF4G_HUMAN', 'GBP3_HUMAN', 'ITIH6_HUMAN', 'ID4_HUMAN', 'GT252_HUMAN', 'HOIL1_HUMAN', 'GLBL3_HUMAN', 'HYCCI_HUMAN',
                     'GBRA4_HUMAN', 'IGF2_HUMAN', 'GG6LA_HUMAN', 'GBA2_HUMAN', 'IDAS1_HUMAN', 'HNRPC_HUMAN', 'IFNK_HUMAN', 'INSL3_HUMAN', 'HLAF_HUMAN', 'IGHG1_HUMAN', 'HXA3_HUMAN', 'GRIK1_HUMAN', 'I22R1_HUMAN', 'GRM2A_HUMAN', 'HSP77_HUMAN', 'I27RA_HUMAN', 'HDAC5_HUMAN', 'HS3S5_HUMAN', 'HECW2_HUMAN', 'GMEB2_HUMAN', 'H33_HUMAN', 'H90B2_HUMAN', 'ISG20_HUMAN', 'HV309_HUMAN', 'GGYF1_HUMAN', 'GL1D1_HUMAN', 'HIS1_HUMAN', 'HDHD2_HUMAN', 'GRM3_HUMAN', 'GRAB_HUMAN', 'ITB5_HUMAN', 'IQCH_HUMAN', 'GP142_HUMAN', 'HSF1_HUMAN', 'I22R2_HUMAN', 'IL18R_HUMAN', 'ITSN2_HUMAN', 'GRP4_HUMAN', 'HPCL1_HUMAN', 'GDF15_HUMAN', 'H2B1L_HUMAN', 'HECA2_HUMAN', 'GCP3_HUMAN', 'GLYL2_HUMAN', 'GPR34_HUMAN', 'GDF11_HUMAN', 'IL1AP_HUMAN', 'HHATL_HUMAN', 'GVQW1_HUMAN', 'IFIT2_HUMAN', 'GRP2_HUMAN', 'GSDMA_HUMAN', 'ID2_HUMAN', 'GRL1A_HUMAN', 'GRPE2_HUMAN', 'I10R1_HUMAN', 'GUCD1_HUMAN', 'HAUS3_HUMAN', 'GA45A_HUMAN', 'HMR1_HUMAN', 'HIBCH_HUMAN', 'GRWD1_HUMAN', 'GLTL5_HUMAN', 'HMN13_HUMAN', 'GLCI1_HUMAN', 'HPPD_HUMAN',
                     'GLTL6_HUMAN', 'IDE_HUMAN', 'HACD4_HUMAN', 'GTPB3_HUMAN', 'G2E3_HUMAN', 'GNAT2_HUMAN', 'HPDL_HUMAN', 'GGA2B_HUMAN', 'HNRH2_HUMAN', 'GEMI7_HUMAN', 'HIF3A_HUMAN', 'GPX8_HUMAN', 'HV205_HUMAN', 'GCFC2_HUMAN', 'H1X_HUMAN', 'HRC23_HUMAN', 'ITBP1_HUMAN', 'HEAT1_HUMAN', 'H90B3_HUMAN', 'HS105_HUMAN', 'GC224_HUMAN', 'HPLN3_HUMAN', 'INMT_HUMAN', 'GABR1_HUMAN', 'GRM5_HUMAN', 'GOR_HUMAN', 'GSAS1_HUMAN', 'HPTR_HUMAN', 'GSAP_HUMAN', 'GPAT4_HUMAN', 'GPTC8_HUMAN', 'H6ST3_HUMAN', 'IF4A2_HUMAN', 'INT4_HUMAN', 'H2A1J_HUMAN', 'GBRA3_HUMAN', 'GSX1_HUMAN', 'HV461_HUMAN', 'HAND2_HUMAN', 'HTSF1_HUMAN', 'GD1L1_HUMAN', 'H11_HUMAN', 'HDC_HUMAN', 'ISK9_HUMAN', 'HORM1_HUMAN', 'GGA3_HUMAN', 'GPX7_HUMAN', 'GTR6_HUMAN', 'HOP_HUMAN', 'HMN5_HUMAN', 'GGNB1_HUMAN', 'GPC5_HUMAN', 'GRP_HUMAN', 'H2A3_HUMAN', 'GLHA_HUMAN', 'HV5X1_HUMAN', 'GALT3_HUMAN', 'HRH4_HUMAN', 'GLCNE_HUMAN', 'GOSR2_HUMAN', 'HS71A_HUMAN', 'HV108_HUMAN', 'ISK6_HUMAN', 'IQCE_HUMAN', 'I20RB_HUMAN', 'HNRPK_HUMAN', 'GAS7_HUMAN',
                     'IL22_HUMAN', 'ICAM2_HUMAN', 'GDPD5_HUMAN', 'GG6LS_HUMAN', 'JAG2_HUMAN', 'IPYR_HUMAN', 'GP156_HUMAN', 'GDC_HUMAN', 'GTPBA_HUMAN', 'GBGT1_HUMAN', 'GFOD2_HUMAN', 'GL8D2_HUMAN', 'GVQW3_HUMAN', 'ISK4_HUMAN', 'GBX2_HUMAN', 'ID2B_HUMAN', 'IFNA2_HUMAN', 'GEPH_HUMAN', 'ITPR1_HUMAN', 'IGS11_HUMAN', 'ITAD_HUMAN', 'IFM3_HUMAN', 'GFY_HUMAN', 'IF140_HUMAN', 'IFM10_HUMAN', 'IMA1_HUMAN', 'GPR87_HUMAN', 'GSTO1_HUMAN', 'GBG11_HUMAN', 'HXD3_HUMAN', 'HV348_HUMAN', 'HEBP2_HUMAN', 'GAPT_HUMAN', 'HCN3_HUMAN', 'GPC2_HUMAN', 'GUC1A_HUMAN', 'HXD4_HUMAN', 'GCNT7_HUMAN', 'GLMN_HUMAN', 'GRD2I_HUMAN', 'HXB3_HUMAN', 'GOSR1_HUMAN', 'GPX3_HUMAN', 'IL20_HUMAN', 'GORS2_HUMAN', 'IG2R_HUMAN', 'HV431_HUMAN', 'IQEC3_HUMAN', 'GAS2_HUMAN', 'HSPB7_HUMAN', 'ISL2_HUMAN', 'GFAP_HUMAN', 'GBRB3_HUMAN', 'GRAP2_HUMAN', 'IER5L_HUMAN', 'GGACT_HUMAN', 'HSPB3_HUMAN', 'IGS10_HUMAN', 'GNAI3_HUMAN', 'GP139_HUMAN', 'IL3RB_HUMAN', 'HIDE1_HUMAN', 'HSP74_HUMAN', 'HES1_HUMAN', 'IREB2_HUMAN', 'ITB4_HUMAN', 'GFRAL_HUMAN',
                     'GPR20_HUMAN', 'HV374_HUMAN', 'ICMT_HUMAN', 'GPR31_HUMAN', 'HELZ2_HUMAN', 'HPF1_HUMAN', 'IQCF3_HUMAN', 'HIF1A_HUMAN', 'IFFO2_HUMAN', 'H2AX_HUMAN', 'H2A1B_HUMAN', 'GATM_HUMAN', 'GAB1_HUMAN', 'IQUB_HUMAN', 'IASPP_HUMAN', 'HAKAI_HUMAN', 'IMA6_HUMAN', 'GPR33_HUMAN', 'GPTC3_HUMAN', 'GSTA5_HUMAN', 'HMDH_HUMAN', 'GPC5B_HUMAN', 'GSDMC_HUMAN', 'GALT7_HUMAN', 'GAAS1_HUMAN', 'IL9_HUMAN', 'IFI27_HUMAN', 'GHC2_HUMAN', 'GRID2_HUMAN', 'ISM2_HUMAN', 'GLRX2_HUMAN', 'HCK_HUMAN', 'ICK_HUMAN', 'IFN16_HUMAN', 'GTR12_HUMAN', 'HCD2_HUMAN', 'ILRUN_HUMAN', 'HXD12_HUMAN', 'GHC1_HUMAN', 'HV145_HUMAN', 'G6PE_HUMAN', 'ITAX_HUMAN', 'HEPC_HUMAN', 'IGFN1_HUMAN', 'HOT_HUMAN', 'HMGC2_HUMAN', 'HYDIN_HUMAN', 'HEG1_HUMAN', 'HV692_HUMAN', 'HNRC3_HUMAN', 'IPMK_HUMAN', 'HV353_HUMAN', 'GLRB_HUMAN', 'GPM6A_HUMAN', 'GBG5_HUMAN', 'IF122_HUMAN', 'ILDR2_HUMAN', 'HINFP_HUMAN', 'INAM2_HUMAN', 'HGF_HUMAN', 'HIPK3_HUMAN', 'HNRPU_HUMAN', 'IFN14_HUMAN', 'I15RA_HUMAN', 'HCLS1_HUMAN', 'HXC10_HUMAN', 'IF2G_HUMAN',
                     'GAPD1_HUMAN', 'IPKB_HUMAN', 'I5P1_HUMAN', 'HV118_HUMAN', 'HNRPR_HUMAN', 'GA2L1_HUMAN', 'IPP2C_HUMAN', 'HPS1_HUMAN', 'GRM2B_HUMAN', 'IF_HUMAN', 'IMDH1_HUMAN', 'INF2_HUMAN', 'H2AZ_HUMAN', 'GATA3_HUMAN', 'GGA1_HUMAN', 'HXC4_HUMAN', 'GRM2_HUMAN', 'GBRA2_HUMAN', 'INVO_HUMAN', 'IMDH2_HUMAN', 'IRX6_HUMAN', 'HXC9_HUMAN', 'HIG2A_HUMAN', 'HABP4_HUMAN', 'GIPC2_HUMAN', 'IF5A1_HUMAN', 'GUC2A_HUMAN', 'GBG7_HUMAN', 'GP171_HUMAN', 'GCYA1_HUMAN', 'IL4_HUMAN', 'GULP1_HUMAN', 'GRHL1_HUMAN', 'HTRA2_HUMAN', 'IGDC3_HUMAN', 'HV459_HUMAN', 'GLDN_HUMAN', 'GRIFN_HUMAN', 'HECD2_HUMAN', 'GEMI6_HUMAN', 'INP5K_HUMAN', 'GP151_HUMAN', 'IMPA3_HUMAN', 'H2AY_HUMAN', 'IPSP_HUMAN', 'GRIK5_HUMAN', 'HXD9_HUMAN', 'IPIL1_HUMAN', 'HCAR1_HUMAN', 'HS3SB_HUMAN', 'JAK1_HUMAN', 'GGE2D_HUMAN', 'GOGA4_HUMAN', 'IRF1_HUMAN', 'HBG1_HUMAN', 'HNRPQ_HUMAN', 'HV321_HUMAN', 'HEBP1_HUMAN', 'GBF1_HUMAN', 'H2B1C_HUMAN', 'GAB2_HUMAN', 'GPRL1_HUMAN', 'I17EL_HUMAN', 'GNPI2_HUMAN', 'IL8_HUMAN', 'HYAS2_HUMAN', 'IF4H_HUMAN',
                     'IFNL1_HUMAN', 'GALT1_HUMAN', 'GRK1_HUMAN', 'GMIP_HUMAN', 'GCST_HUMAN', 'GALR2_HUMAN', 'HES5_HUMAN', 'GTR8_HUMAN', 'HJURP_HUMAN', 'HMGN4_HUMAN', 'HM13_HUMAN', 'ISCA2_HUMAN', 'GADL1_HUMAN', 'GTSC1_HUMAN', 'HXB2_HUMAN', 'ICAM5_HUMAN', 'HCP5_HUMAN', 'H2A1C_HUMAN', 'IF2A_HUMAN', 'HTR5B_HUMAN', 'ILRL2_HUMAN', 'GKN2_HUMAN', 'HIS3_HUMAN', 'GEMI2_HUMAN', 'HEY2_HUMAN', 'HPF1L_HUMAN', 'IBP5_HUMAN', 'IF4G3_HUMAN', 'GLE1_HUMAN', 'IGHG2_HUMAN', 'ILF3_HUMAN', 'ICE2_HUMAN', 'GBP5_HUMAN', 'GOGA1_HUMAN', 'GBP6_HUMAN', 'GPSM2_HUMAN', 'GRHL2_HUMAN', 'IRAK4_HUMAN', 'GRPE1_HUMAN', 'HES3_HUMAN', 'GRAP1_HUMAN', 'HPLN4_HUMAN', 'HTAI2_HUMAN', 'HPS6_HUMAN', 'GGT6_HUMAN', 'HEMK1_HUMAN', 'GBRG3_HUMAN', 'H2B2C_HUMAN', 'IKBA_HUMAN', 'GBRB2_HUMAN', 'IPO4_HUMAN', 'GPR32_HUMAN', 'IRF6_HUMAN', 'GG12H_HUMAN', 'ITB6_HUMAN', 'HSP7E_HUMAN', 'IGHA1_HUMAN', 'GL6D1_HUMAN', 'INCA1_HUMAN', 'GCSH_HUMAN', 'IMP4_HUMAN', 'HYI_HUMAN', 'HERC5_HUMAN', 'HES4_HUMAN', 'ING1_HUMAN', 'GPC3_HUMAN', 'G6PC2_HUMAN',
                     'HELT_HUMAN', 'HSBP1_HUMAN', 'INSL6_HUMAN', 'INSC_HUMAN', 'H1BP3_HUMAN', 'GELS_HUMAN', 'IFRD1_HUMAN', 'HV124_HUMAN', 'GNAS1_HUMAN', 'GABT_HUMAN', 'IGLL1_HUMAN', 'HXA5_HUMAN', 'GCOM2_HUMAN', 'GLU2B_HUMAN', 'I18BP_HUMAN', 'GTR9_HUMAN', 'HLAG_HUMAN', 'GATA2_HUMAN', 'HXB6_HUMAN', 'GP173_HUMAN', 'GP180_HUMAN', 'IQCK_HUMAN', 'GRIA1_HUMAN', 'HBP1_HUMAN', 'IPO11_HUMAN', 'GOG8M_HUMAN', 'GGN_HUMAN', 'HMBX1_HUMAN', 'GIMA5_HUMAN', 'GOG8I_HUMAN', 'IZUM1_HUMAN', 'GLT12_HUMAN', 'GP135_HUMAN', 'HECD4_HUMAN', 'G6PD_HUMAN', 'GBRA6_HUMAN', 'GON7_HUMAN', 'GP1BB_HUMAN', 'HINT1_HUMAN', 'GALNS_HUMAN', 'GOLM1_HUMAN', 'GG6LV_HUMAN', 'HV64D_HUMAN', 'GRCR1_HUMAN', 'IKZF3_HUMAN', 'IL36G_HUMAN', 'HSDL1_HUMAN', 'IMPCT_HUMAN', 'GATA_HUMAN', 'INHA_HUMAN', 'IPO9_HUMAN', 'HHAT_HUMAN', 'IBP7_HUMAN', 'IF2GL_HUMAN', 'GNAT3_HUMAN', 'HEMH_HUMAN', 'GAS1_HUMAN', 'GPD1L_HUMAN', 'GLRA2_HUMAN', 'GRIK4_HUMAN', 'HV601_HUMAN', 'ITPK1_HUMAN', 'HYAL3_HUMAN', 'GOGB1_HUMAN', 'HBAZ_HUMAN', 'G6PT1_HUMAN',
                     'GOPC_HUMAN', 'GUC2B_HUMAN', 'HV366_HUMAN', 'HXA2_HUMAN', 'GPTC2_HUMAN', 'GIMA2_HUMAN', 'IOD1_HUMAN', 'H2B1B_HUMAN', 'GCR_HUMAN', 'GUF1_HUMAN', 'GLRX3_HUMAN', 'IGFL1_HUMAN', 'GAG2E_HUMAN', 'GNPI1_HUMAN', 'HECAM_HUMAN', 'GMFG_HUMAN', 'GSC_HUMAN', 'GPR12_HUMAN', 'HDAC9_HUMAN', 'GARL3_HUMAN', 'IL3RA_HUMAN', 'GAK1B_HUMAN', 'HV313_HUMAN', 'IQEC1_HUMAN', 'IKKB_HUMAN', 'GGEE3_HUMAN', 'GILT_HUMAN', 'HMGA1_HUMAN', 'GPR84_HUMAN', 'GEM_HUMAN', 'HCFC1_HUMAN', 'INP4A_HUMAN', 'JAGN1_HUMAN', 'HS12B_HUMAN', 'HS71B_HUMAN', 'HRG1_HUMAN', 'GEMC1_HUMAN', 'H2B1H_HUMAN', 'IDI2_HUMAN', 'GTPB8_HUMAN', 'HV372_HUMAN', 'IQCF2_HUMAN', 'HYES_HUMAN', 'GP160_HUMAN', 'GSTA4_HUMAN', 'IAPP_HUMAN', 'HV343_HUMAN', 'GAK24_HUMAN', 'HECW1_HUMAN', 'IGFL4_HUMAN', 'ITBP2_HUMAN', 'GAK5_HUMAN', 'IL12B_HUMAN', 'GLUT4_HUMAN', 'IRX3_HUMAN', 'HLAC_HUMAN', 'HXD1_HUMAN', 'GA113_HUMAN', 'GRHPR_HUMAN', 'GSTT4_HUMAN', 'HCST_HUMAN', 'HV70D_HUMAN', 'GATA6_HUMAN', 'GNA14_HUMAN', 'IF6_HUMAN', 'GDF5_HUMAN',
                     'IRPL1_HUMAN', 'HXK4_HUMAN', 'HOGA1_HUMAN', 'GAGE5_HUMAN', 'INPP_HUMAN', 'H2A2B_HUMAN', 'HYPM_HUMAN', 'HPLN2_HUMAN', 'GUC1C_HUMAN', 'INE1_HUMAN', 'GDNF_HUMAN', 'ISX_HUMAN', 'IER5_HUMAN', 'GLYL1_HUMAN', 'HHLA2_HUMAN', 'IF4E2_HUMAN', 'H10_HUMAN', 'HLX_HUMAN', 'HS3SA_HUMAN', 'INT9_HUMAN', 'HXB1_HUMAN', 'HNRC2_HUMAN', 'HAOX1_HUMAN', 'ILK_HUMAN', 'GBG8_HUMAN', 'GPKOW_HUMAN', 'GAS6_HUMAN', 'HYAS3_HUMAN', 'INTU_HUMAN', 'GKN3_HUMAN', 'IGLC6_HUMAN', 'GPBP1_HUMAN', 'GP146_HUMAN', 'GALT9_HUMAN', 'GNA12_HUMAN', 'INSI2_HUMAN', 'HOOK3_HUMAN', 'GAGE1_HUMAN', 'H6ST1_HUMAN', 'GREM2_HUMAN', 'IGSF3_HUMAN', 'HV333_HUMAN', 'GRIA4_HUMAN', 'HMX2_HUMAN', 'HYAL1_HUMAN', 'G6PC3_HUMAN', 'IMPG1_HUMAN', 'HESX1_HUMAN', 'GHSR_HUMAN', 'IGSF1_HUMAN', 'GNA13_HUMAN', 'GCSP_HUMAN', 'GP161_HUMAN', 'IL6RB_HUMAN', 'GBB3_HUMAN', 'IFT22_HUMAN', 'HJ01_HUMAN', 'GFPT2_HUMAN', 'I4E1B_HUMAN', 'IL7RA_HUMAN', 'ITPI1_HUMAN', 'GOG8D_HUMAN', 'GIPC3_HUMAN', 'HAND1_HUMAN', 'GRAA_HUMAN', 'HDGR2_HUMAN', 'HRH2_HUMAN',
                     'GPR3_HUMAN', 'HVD34_HUMAN', 'HSF2B_HUMAN', 'GPR37_HUMAN', 'INAM1_HUMAN', 'IFT74_HUMAN', 'HMN11_HUMAN', 'HKDC1_HUMAN', 'GBRR1_HUMAN', 'GDPD1_HUMAN', 'GOG7B_HUMAN', 'GNAZ_HUMAN', 'INSL4_HUMAN', 'IAH1_HUMAN', 'HV102_HUMAN', 'HAUS7_HUMAN', 'IST1_HUMAN', 'ISCA1_HUMAN', 'I5P2_HUMAN', 'GAB4_HUMAN', 'JAML_HUMAN', 'HVC05_HUMAN', 'IPP_HUMAN', 'HV551_HUMAN', 'ICAM1_HUMAN', 'IL12A_HUMAN', 'HAP1_HUMAN', 'H15_HUMAN', 'H90B4_HUMAN', 'HBB_HUMAN', 'INAR1_HUMAN', 'GWL_HUMAN', 'H2B1N_HUMAN', 'H2BFM_HUMAN', 'INSR2_HUMAN', 'HOME1_HUMAN', 'IGHG4_HUMAN', 'GPR15_HUMAN', 'GCKR_HUMAN', 'IFNL2_HUMAN', 'GPR17_HUMAN', 'HGH1_HUMAN', 'IFIT5_HUMAN', 'INHBB_HUMAN', 'GPC5C_HUMAN', 'IDUA_HUMAN', 'H2A1D_HUMAN', 'GSH0_HUMAN', 'GLCE_HUMAN', 'IPO5_HUMAN', 'GPN1_HUMAN', 'GLPK2_HUMAN', 'HXB13_HUMAN', 'GLD2_HUMAN', 'IHH_HUMAN', 'IL24_HUMAN', 'GINM1_HUMAN', 'GG6L9_HUMAN', 'GLT15_HUMAN', 'GLYM_HUMAN', 'G6PT2_HUMAN', 'HMN3_HUMAN', 'ITAL_HUMAN', 'IPYR2_HUMAN', 'IFRD2_HUMAN', 'GLPK5_HUMAN', 'GOG8R_HUMAN',
                     'I2BP2_HUMAN', 'IDHC_HUMAN', 'HD_HUMAN', 'H2BFS_HUMAN', 'GREM1_HUMAN', 'HS12A_HUMAN', 'HOMEZ_HUMAN', 'IGFL3_HUMAN', 'HBA_HUMAN', 'IFN17_HUMAN', 'GXLT2_HUMAN', 'GP155_HUMAN', 'GLT16_HUMAN', 'GRIK2_HUMAN', 'I36RA_HUMAN', 'HMN2_HUMAN', 'GSTM3_HUMAN', 'GAR1_HUMAN', 'INP5E_HUMAN', 'GNS_HUMAN', 'GCDH_HUMAN', 'GFPT1_HUMAN', 'GPC6_HUMAN', 'GTPB2_HUMAN', 'HCN1_HUMAN', 'GTR14_HUMAN', 'IQCAL_HUMAN', 'GNA15_HUMAN', 'H2AB1_HUMAN', 'GRAP_HUMAN', 'GNAT1_HUMAN', 'GPR45_HUMAN', 'ITM2C_HUMAN', 'I23O2_HUMAN', 'HYEP_HUMAN', 'ISM1_HUMAN', 'HPBP1_HUMAN', 'HSC20_HUMAN', 'ITPI2_HUMAN', 'HDGL1_HUMAN', 'GIT1_HUMAN', 'GPNMB_HUMAN', 'IC1_HUMAN', 'GDIR3_HUMAN', 'H2B1M_HUMAN', 'HV43D_HUMAN', 'H1FOO_HUMAN', 'HSFY1_HUMAN', 'HSDL2_HUMAN', 'GMCL2_HUMAN', 'GSTA1_HUMAN', 'HV404_HUMAN', 'IFNG_HUMAN', 'IF5_HUMAN', 'IRF3_HUMAN', 'HIG2B_HUMAN', 'ITA9_HUMAN', 'ICE1_HUMAN', 'HBD_HUMAN', 'HXC13_HUMAN', 'HLAE_HUMAN', 'IL5RA_HUMAN', 'GFRA3_HUMAN', 'IL27B_HUMAN', 'GSTO2_HUMAN', 'H2B2D_HUMAN', 'GCSAM_HUMAN',
                     'GBB4_HUMAN', 'GMPPB_HUMAN', 'GPDM_HUMAN', 'HAVR1_HUMAN', 'IL7_HUMAN', 'GID8_HUMAN', 'HMGN1_HUMAN', 'IKZF4_HUMAN', 'HMN9_HUMAN', 'GUAA_HUMAN', 'H32_HUMAN', 'HMGB3_HUMAN', 'GDIR1_HUMAN', 'ICAM4_HUMAN', 'ITA10_HUMAN', 'HS90B_HUMAN', 'IER2_HUMAN', 'INSM2_HUMAN', 'IRPL2_HUMAN', 'GCNT1_HUMAN', 'HES6_HUMAN', 'IFT88_HUMAN', 'GRN_HUMAN', 'HSPB2_HUMAN', 'I17RA_HUMAN', 'IMP1L_HUMAN', 'GRIP1_HUMAN', 'IMB1_HUMAN', 'G3ST2_HUMAN', 'H2BWT_HUMAN', 'ID1_HUMAN', 'ISOC2_HUMAN', 'GUC2F_HUMAN', 'GDF9_HUMAN', 'IRF7_HUMAN', 'ING5_HUMAN', 'IMP3_HUMAN', 'HS2ST_HUMAN', 'IKBB_HUMAN', 'IRF4_HUMAN', 'GALT8_HUMAN', 'GLCTK_HUMAN', 'ICAL_HUMAN', 'IL40_HUMAN', 'IP6K2_HUMAN', 'IL1R1_HUMAN', 'JARD2_HUMAN', 'HNRLL_HUMAN', 'HEM0_HUMAN', 'GGYF2_HUMAN', 'HV373_HUMAN', 'H12_HUMAN', 'IFNA1_HUMAN', 'IRG1_HUMAN', 'INSY1_HUMAN', 'ISK2_HUMAN', 'GOT1B_HUMAN', 'GMPR1_HUMAN', 'IGSF2_HUMAN', 'HRH1_HUMAN', 'IPRI_HUMAN', 'GALP_HUMAN', 'HPRT_HUMAN', 'IL1R2_HUMAN', 'H13_HUMAN', 'GDF1_HUMAN', 'HUS1_HUMAN',
                     'HIPK2_HUMAN', 'GVIN1_HUMAN', 'GPR25_HUMAN', 'H1AS1_HUMAN', 'IFT27_HUMAN', 'GHRHR_HUMAN', 'GBRL2_HUMAN', 'GDN_HUMAN', 'HHIP_HUMAN', 'ITA8_HUMAN', 'GG6L7_HUMAN', 'IP3KA_HUMAN', 'IF4A3_HUMAN', 'ING4_HUMAN', 'GLPK_HUMAN', 'GAGE6_HUMAN', 'GPX2_HUMAN', 'HOOK1_HUMAN', 'GRID1_HUMAN', 'ILEU_HUMAN', 'HEAT3_HUMAN', 'IRAK3_HUMAN', 'GSTA2_HUMAN', 'HYAL4_HUMAN', 'HGFA_HUMAN', 'GLYR1_HUMAN', 'HMCS1_HUMAN', 'HXA9_HUMAN', 'IZUM4_HUMAN', 'HEXD_HUMAN', 'H2A1_HUMAN', 'IGBP1_HUMAN', 'GAL3A_HUMAN', 'HES2_HUMAN', 'HPS4_HUMAN', 'ITIH5_HUMAN', 'GALT4_HUMAN', 'HMN1_HUMAN', 'GEMI4_HUMAN', 'IRGM_HUMAN', 'IGS23_HUMAN', 'GNA1_HUMAN', 'HAUS1_HUMAN', 'ITB3_HUMAN', 'ISK1_HUMAN', 'H2AB2_HUMAN', 'INY2B_HUMAN', 'ISOC1_HUMAN', 'GTR5_HUMAN', 'GGT7_HUMAN', 'IMA8_HUMAN', 'HMGCL_HUMAN', 'GRB14_HUMAN', 'GALR3_HUMAN', 'HERC3_HUMAN', 'GGT3_HUMAN', 'HMCS2_HUMAN', 'HDHD3_HUMAN', 'HXD10_HUMAN', 'HTD2_HUMAN', 'GRP1_HUMAN', 'GDPD3_HUMAN', 'HPT_HUMAN', 'GP15L_HUMAN', 'HXA10_HUMAN', 'ITA5_HUMAN', 'HAUS4_HUMAN']
        # ENSP_2_functionEnumArray_dict = get_functionEnumArray_from_proteins(ensp_list, dict_2_array=True)
        print(get_functionEnumArray_from_proteins(ensp_list[:3], dict_2_array=True))
        print(get_functionEnumArray_from_proteins(ensp_list[:3], dict_2_array=False))



    # fg = np.random.randint(0, 5000000, 200)
    # bg = np.random.randint(0, 5000000, 20000)
    # # res_dbl_fg = searchsorted_dbl(fg, bg)
    # fg_bg = np.concatenate((fg, bg))
    # np.searchsorted(fg, fg_bg)
    # fg = np.arange(0, 5)
    # bg = np.arange(3, 10)
    # fg_bg = np.concatenate((fg, bg))
    # fg_bg.sort()
    # res = searchsorted_dbl(fg, fg_bg)
    # print(res)
    # fg = [0,1,1,2,2,2,4,5,6]
    # fg = np.array(fg)
    # bg = [0, 1, 1, 2, 2, 2, 4, 5, 6, 10,1000]
    # bg = np.array(bg)
    # res_dbl_fg = searchsorted_dbl(fg, bg)
    # fg_bg = np.concatenate((fg, bg))
    # fg_bg.sort()
    # res_np_fg = np.searchsorted(fg, fg_bg, side="right")
    # res_np_bg = np.searchsorted(bg, fg_bg, side="right")
    # print(res_np_fg)
    # print(fg_bg)
    # print(fg)
    # print(res_dbl_fg)
    # same = (res_dbl_fg == res_np_fg).all()
    # if not same:
    #     print(res_dbl_fg)
    #     print(res_np_fg)
    # assert (res_dbl_bg == res_np_bg).all()
    # np.random.seed(12345)
    # counter = 0
    # for num_iter in range(10000):
    #     fg = np.random.randint(0, 5000000, 200)
    #     bg = np.random.randint(0, 5000000, 20000)
    #     fg_bg = np.concatenate((fg, bg))
    #     fg_bg.sort()
    #     res_dbl = searchsorted_dbl(fg, bg)
    #     res_np = np.searchsorted(fg, fg_bg, side="right")
    #     same = (res_dbl_fg == res_np_fg).all()
    #     if not same:
    #         print(res_dbl_fg)
    #         print(res_np_fg)
    #         break
    #     else:
    #         counter += 1
    #     assert (res_dbl_fg == res_np_fg).all()
    # print(counter)

    # from scipy import stats
    # stats.ks_2samp()